export const SET_ADVENTURES = 'SET_ADVENTURES';
export const GET_ADVENTURES = 'GET_ADVENTURES';
export const GET_POPULAR_ADVENTURES = 'GET_POPULAR_ADVENTURES';
export const SET_POPULAR_ADVENTURES = 'SET_POPULAR_ADVENTURES';
export const SET_ADVENTURES_IS_LOADING = 'SET_ADVENTURES_IS_LOADING';
export const SET_ADVENTURES_ERROR = 'SET_ADVENTURES_ERROR';
export const SET_HAS_MORE_ADVENTURES = 'SET_HAS_MORE_ADVENTURES';
