export const SET_ADVENTURES = 'SET_ADVENTURES';
export const GET_ADVENTURES = 'GET_ADVENTURES';
export const SET_ADVENTURES_IS_LOADING = 'SET_ADVENTURES_IS_LOADING';
export const SET_ADVENTURES_ERROR = 'SET_ADVENTURES_ERROR';
