export const SET_ADVENTURES = 'SET_ADVENTURES';
export const GET_ADVENTURES = 'GET_ADVENTURES';
export const SET_ADVENTURES_IS_LOADING = 'SET_ADVENTURES_IS_LOADING';
export const SET_ADVENTURES_ERROR = 'SET_ADVENTURES_ERROR';
export const SET_HAS_MORE_ADVENTURES = 'SET_HAS_MORE_ADVENTURES';
export const CLEAR_ADVENTURES = 'CLEAR_ADVENTURES';

export const GET_POPULAR_ADVENTURES = 'GET_POPULAR_ADVENTURES';
export const SET_POPULAR_ADVENTURES = 'SET_POPULAR_ADVENTURES';
export const SET_POPULAR_ADVENTURES_STARTED = 'SET_POPULAR_ADVENTURES_STARTED';

export const SAVE_ADVENTURE = 'SAVE_ADVENTURE';
export const LIKE_ADVENTURE_STARTED = 'LIKE_ADVENTURE_STARTED';
export const DELETE_SAVED_ADVENTURE = 'DELETE_SAVED_ADVENTURE';
export const DELETE_SAVED_ADVENTURE_COMPLETED =
  'DELETE_SAVED_ADVENTURE_COMPLETED';

export const ADD_VISITED_ADVENTURE = 'ADD_VISITED_ADVENTURE';
export const ADD_VISITED_ADVENTURE_STARTED = 'ADD_VISITED_ADVENTURE_STARTED';
export const ADD_VISITED_ADVENTURE_COMPLETED =
  'ADD_VISITED_ADVENTURE_COMPLETED';

export const DELETE_VISITED_ADVENTURE = 'DELETE_VISITED_ADVENTURE';
export const DELETE_VISITED_ADVENTURE_STARTED =
  'DELETE_VISITED_ADVENTURE_STARTED';
export const DELETE_VISITED_ADVENTURE_COMPLETED =
  'DELETE_VISITED_ADVENTURE_COMPLETED';

export const ADD_ADVENTURE_REVIEW = 'ADD_ADVENTURE_REVIEW';
export const GET_ADVENTURE_REVIEW = 'GET_ADVENTURE_REVIEW';

export const GET_ADVENTURES_BY_DESTINATION = 'GET_ADVENTURES_BY_DESTINATION';

export const UPDATE_ADVENTURE_STARTED = 'UPDATE_ADVENTURE_STARTED';
export const UPDATE_ADVENTURE = 'UPDATE_ADVENTURE';
export const UPDATE_ADVENTURE_COMPLETED = 'UPDATE_ADVENTURE_COMPLETED';

export const ADD_ADVENTURE_STARTED = 'ADD_ADVENTURE_STARTED';
export const ADD_ADVENTURE = 'ADD_ADVENTURE';
export const ADD_ADVENTURE_COMPLETED = 'ADD_ADVENTURE_COMPLETED';

export const DELETE_ADVENTURE_STARTED = 'DELETE_ADVENTURE_STARTED';
export const DELETE_ADVENTURE = 'DELETE_ADVENTURE';
export const DELETE_ADVENTURE_COMPLETED = 'DELETE_ADVENTURE_COMPLETED';
