export const SET_USER = 'SET_USER';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';

export const LOG_IN_USER = 'LOG_IN_USER';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const SING_UP_USER = 'SING_UP_USER';

export const SET_LOG_IN_IS_LOADING = 'SET_LOG_IN_IS_LOADING';
export const SET_LOG_OUT_IS_LOADING = 'SET_LOG_OUT_IS_LOADING';
export const SET_SIGN_UP_IS_LOADING = 'SET_SING_UP_IS_LOADING';

export const SET_LOG_IN_ERROR = 'SET_LOG_IN_ERROR';
export const SET_LOG_OUT_ERROR = 'SET_LOG_OUT_ERROR';
export const SET_SIGN_UP_ERROR = 'SET_SING_UP_ERROR';

export const SET_IS_ONBOARDING = 'SET_IS_ONBOARDING';
export const SAVE_PROFILE_ONBOARDING = 'SAVE_PROFILE_ONBOARDING';

export const SET_SAVED_HOTEL = 'SET_SAVED_HOTEL';
export const SET_SAVED_ADVENTURE = 'SET_SAVED_ADVENTURE';

export const DELETE_USER_STARTED = 'DELETE_USER_STARTED';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_COMPLETED = 'DELETE_USER_COMPLETED';

export const UPDATE_USER_STARTED = 'UPDATE_USER_STARTED';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_COMPLETED = 'UPDATE_USER_COMPLETED';
