export const SET_DESTINATIONS = 'SET_DESTINATIONS';
export const GET_DESTINATIONS = 'GET_DESTINATIONS';
export const GET_POPULAR_DESTINATIONS = 'GET_POPULAR_DESTINATIONS';
export const SET_POPULAR_DESTINATIONS = 'SET_POPULAR_DESTINATIONS';
export const SET_POPULAR_DESTINATIONS_STARTED =
  'SET_POPULAR_DESTINATIONS_STARTED';

export const SET_DESTINATIONS_IS_LOADING = 'SET_DESTINATIONS_IS_LOADING';
export const SET_DESTINATIONS_ERROR = 'SET_DESTINATIONS_ERROR';
export const SET_HAS_MORE_DESTINATIONS = 'SET_HAS_MORE_DESTINATIONS';

export const CLEAR_DESTINATIONS = 'CLEAR_DESTINATIONS';

export const GET_DESTINATIONS_BY_NAME = 'GET_DESTINATIONS_BY_NAME';
export const GET_DESTINATIONS_BY_NAME_COMPLETED =
  'GET_DESTINATIONS_BY_NAME_COMPLETED';
