export const SET_DESTINATIONS = 'SET_DESTINATIONS';
export const GET_DESTINATIONS = 'GET_DESTINATIONS';
export const SET_DESTINATIONS_IS_LOADING = 'SET_DESTINATIONS_IS_LOADING';
export const SET_DESTINATIONS_ERROR = 'SET_DESTINATIONS_ERROR';
