export const GET_GUIDES = 'GET_GUIDES';
export const SET_GUIDES_STARTED = 'SET_GUIDES_STARTED';
export const SET_GUIDES_COMPLETED = 'SET_GUIDES_COMPLETED';
export const SET_GUIDES_ERROR = 'SET_GUIDES_ERROR';

export const SET_HAS_MORE_GUIDES = 'SET_HAS_MORE_GUIDES';
