export const SET_HOTELS = 'SET_HOTELS';
export const GET_HOTELS_BY_DESTINATION = 'GET_HOTELS_BY_DESTINATION';
export const GET_HOTELS = 'GET_HOTELS';
export const SET_HOTELS_IS_LOADING = 'SET_HOTELS_IS_LOADING';
export const SET_HAS_MORE_HOTELS = 'SET_HAS_MORE_HOTELS';
export const SET_HOTELS_ERROR = 'SET_HOTELS_ERROR';

export const GET_POPULAR_HOTELS = 'GET_POPULAR_HOTELS';
export const SET_POPULAR_HOTELS = 'SET_POPULAR_HOTELS';
export const SET_POPULAR_HOTELS_STARTED = 'SET_POPULAR_HOTELS_STARTED';

export const CLEAR_HOTELS = 'CLEAR_HOTELS';

export const SAVE_HOTEL = 'SAVE_HOTEL';
export const LIKE_HOTEL_STARTED = 'LIKE_HOTEL_STARTED';
export const DELETE_SAVED_HOTEL_COMPLETED = 'DELETE_SAVED_HOTEL_COMPLETED';
export const DELETE_SAVED_HOTEL = 'DELETE_SAVED_HOTEL';

export const ADD_VISITED_HOTEL = 'ADD_VISITED_HOTEL';
export const ADD_VISITED_HOTEL_STARTED = 'ADD_VISITED_HOTEL_STARTED';
export const ADD_VISITED_HOTEL_COMPLETED = 'ADD_VISITED_HOTEL_COMPLETED';

export const DELETE_VISITED_HOTEL = 'DELETE_VISITED_HOTEL';
export const DELETE_VISITED_HOTEL_STARTED = 'DELETE_VISITED_HOTEL_STARTED';
export const DELETE_VISITED_HOTEL_COMPLETED = 'DELETE_VISITED_HOTEL_COMPLETED';

export const ADD_HOTEL_REVIEW = 'ADD_HOTEL_REVIEW';

export const UPDATE_HOTEL = 'UPDATE_HOTEL';
export const SET_HOTEL = 'SET_HOTEL';

export const UPDATE_HOTEL_GALLERY = 'UPDATE_HOTEL_GALLERY';

export const DELETE_GALLERY_IMAGE = 'DELETE_GALLERY_IMAGE';
export const DELETE_GALLERY_IMAGE_COMPLETED = 'DELETE_GALLERY_IMAGE_COMPLETED';

export const ADD_HOTEL = 'ADD_HOTEL';
export const ADD_HOTEL_COMPLETED = 'ADD_HOTEL_COMPLETED';

export const DELETE_HOTEL_STARTED = 'DELETE_HOTEL_STARTED';
export const DELETE_HOTEL = 'DELETE_HOTEL';
export const DELETE_HOTEL_COMPLETED = 'DELETE_HOTEL_COMPLETED';
