export const SET_HOTELS = 'SET_HOTELS';
export const GET_HOTELS = 'GET_HOTELS';
export const GET_POPULAR_HOTELS = 'GET_POPULAR_HOTELS';
export const SET_POPULAR_HOTELS = 'SET_POPULAR_HOTELS';
export const SET_HAS_MORE_HOTELS = 'SET_HAS_MORE_HOTELS';
export const SET_HOTELS_IS_LOADING = 'SET_HOTELS_IS_LOADING';
export const SET_HOTELS_ERROR = 'SET_HOTELS_ERROR';
export const CLEAR_HOTELS = 'CLEAR_HOTELS';
